### ISSUE TITLE
fix: Reporting of malformed licenses

### ISSUE THREAD

**Issue by dominicmh** [VeryGoodOpenSource/very_good_cli#1016]
**Description**
`very_good packages check licenses` fails to report pubs with unknown licenses (e.g. [rxdart 0.27.7](https://pub.dev/packages/rxdart/versions/0.27.7)):
```bash
$ very_good packages check licenses
✓ Retrieved 0 licenses from 1 package. (0.7s)
```

**Steps To Reproduce**

1. Clone [example repo](https://github.com/dominicmh/license_check) (includes `rxdart` dependency in `pubspec.lock`)
2. Execute `dart pub global activate very_good_cli; very_good packages check licenses`

**Expected Behavior**
`✓ Retrieved 1 license from 1 package of type: unknown (1).`

**Actual Behavior**
`✓ Retrieved 0 licenses from 1 package.`

**Comment by alestiago** [comment]
Hi @dominicmh thanks for opening an issue! And sorry for the late reply, I haven't been able to catch-up recently.

I've been able to reproduce this issue by using the following `pubspec.yaml`:

```yaml
name: example
description: An example project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  rxdart: ^0.27.7
```

Indeed the output is:
```sh
✓ Retrieved 0 licenses from 1 package. (0.6s)
```

@dominicmh are you interested in contributing with a fix? If so, let me know and I can assign you to this item and assist you on landing it 🙌
