### ISSUE TITLE
fix: No hosted dependencies found in [project directory] of type: direct-main.

### ISSUE THREAD

**Issue by charles0122** [VeryGoodOpenSource/very_good_cli#1150]
### Description

```shell

arce@ArcedeiMac ~ % very_good create flutter_app the_ninth_art --desc "My new Flutter app" --org "top.arce.theninthart"
✓ Generated 303 file(s) (8.0s)
✓ Running "flutter pub get" in .  (3.6s)
✓ Running "dart fix --apply" in ./the_ninth_art (6.1s)


Created a Very Good App! 🦄
  • To get started refer to the_ninth_art/README.md
  • Your project code is in the_ninth_art

+----------------------------------------------------+
| Looking for more features?                         |
| We have an enterprise-grade solution for companies |
| called Very Good Start.                            |
|                                                    |
| For more info visit:                               |
| https://verygood.ventures/solution/very-good-start |
+----------------------------------------------------+

Update available! 0.22.2 → 0.23.1
Changelog: https://github.com/verygoodopensource/very_good_cli/releases/tag/v0.23.1
Run very_good update to update
arce@ArcedeiMac ~ % cd the_ninth_art 
arce@ArcedeiMac the_ninth_art % very_good packages check licenses
No hosted dependencies found in /Users/arce/the_ninth_art of type: direct-main.

Update available! 0.22.2 → 0.23.1
Changelog: https://github.com/verygoodopensource/very_good_cli/releases/tag/v0.23.1
Run very_good update to update
arce@ArcedeiMac the_ninth_art % very_good packages get           
✓ Running "flutter pub get" in .  (1.4s)

Update available! 0.22.2 → 0.23.1
Changelog: https://github.com/verygoodopensource/very_good_cli/releases/tag/v0.23.1
Run very_good update to update
arce@ArcedeiMac the_ninth_art % very_good packages check licenses
No hosted dependencies found in /Users/arce/the_ninth_art of type: direct-main.

Update available! 0.22.2 → 0.23.1
Changelog: https://github.com/verygoodopensource/very_good_cli/releases/tag/v0.23.1
Run very_good update to update

```

### Steps To Reproduce

```shell
very_good create flutter_app the_ninth_art --desc "My new Flutter app" --org "top.arce.theninthart" \
very_good packages check licenses
```

### Expected Behavior

check licenses command execute.

**Comment by alestiago** [comment]
I was unable to reproduce by doing:

```sh
very_good create flutter_app the_ninth_art --desc "My new Flutter app" --org "top.arce.theninthart" \
cd the_ninth_art
very_good packages check licenses
```

I got:
```txt
✓ Retrieved 3 licenses from 3 packages of type: MIT (2) and BSD-3-Clause (1). (0.8s)
```

The `pubspec.yaml` of the created project looks like:

```yaml
name: the_ninth_art
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
```

I was using Very Good Cli 0.23.1.
