### ISSUE TITLE
fix: very_good packages get gets stuck when using dependency via git https link but not authenticated

### ISSUE THREAD

**Issue by orestesgaolin** [VeryGoodOpenSource/very_good_cli#372]
**Description**
When using pubspec.yaml dependency via https git url, but by default ssh authentication is used (so no ability to clone repository via https), the cli hangs. This caused us some problems as the CI was stuck for many hours on the dependency resolving step.

**Steps To Reproduce**

0. Use ssh instead of https authentication on GitHub
1. Add pubspec.yaml dependency using https link to a private GitHub repository e.g.   
```yaml 
my_package:
    git:
      url: https://github.com/org/package.git
      ref: 1a61e2a62094aaf7614a4f8a0063863d21cc6e44
```
2. Run `very_good packages get`
3. See following prompt indefinitely

```sh
❯ very_good packages get
⠋ Running "flutter packages get" in⠸ Running "flutter packages get" in /Users/...
```

**Expected Behavior**
The action should fail with the clear information

**Additional Context**

Maybe timeout would be useful?
