### ISSUE TITLE
feat: lock flutter version in pubspec.yaml

### ISSUE THREAD

**Issue by jdebecka** [VeryGoodOpenSource/very_good_cli#453]
**Description**

Define the version of flutter in pubspec.yaml. I have been personally affected by not adding the line to lock the flutter. Usually, there is still a developer on the project who knows the flutter version but I was in the project where this was not the case. It is hard to determine which Flutter version the project should be run on and we could avoid a guessing game by adding this one line of code. Additionally, it helps the folks who use FVM. 

**Expected Behavior**
```
name: sample_application
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
```
