### ISSUE TITLE
fix: Golden tests always fail in gitub Actions with very_good_workflows

### ISSUE THREAD

**Issue by NickalasB** [VeryGoodOpenSource/very_good_cli#548]
**Description**
Golden tests seem to always fail the `Run tests` step in projects created with `very_good_cli`

**Steps To Reproduce**

1. Create a new project with `very_good_cli`
2. Create a new remote repository for this project, on github
3. add the `test_optimization: false` flag to`.github/workflows/main.yaml` as outlined in the [very_good_workflows ReadMe](https://github.com/VeryGoodOpenSource/very_good_workflows#test_optimization), to allow Golden tests to work (this failure happens regardless of this `test_optimization` being set to true or false)
    
```
name: example

on: [pull_request, push]

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.3.6
      test_optimization: false
```
5. Change the `renders CounterView` test to a Golden test
   
```
    testWidgets('renders CounterView', (tester) async {
      await tester.pumpApp(const CounterPage());
      await expectLater(
        find.byType(CounterPage),
        matchesGoldenFile('goldens/counter_page.png'),
      );
    });
```
 
6. run `flutter test --update-goldens`
7. Commit  and push your project to your remote repository

**Expected Behavior**
The `Run Tests` step in the `Actions` tab should pass

**Actual Behavior**
The `Run Tests` step always fails with a pixel diff issue
<img width="742" alt="Screen Shot 2022-11-03 at 10 58 49 PM" src="https://user-images.githubusercontent.com/16969303/199901724-68ab907a-5b87-496c-b58b-379e2a4cfa63.png">

**Screenshots**

**Additional Context**
I created an example repo with the exact above steps that can be found here - https://github.com/NickalasB/example
The failed Actions step link is here https://github.com/NickalasB/example/actions/runs/3391490409/jobs/5636701481

<details>
<summary>Flutter doctor</summary>
<br>
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>
