### ISSUE TITLE
I Cant start project on Flutter 3.10.0 

### ISSUE THREAD

**Issue by BGM-109** [VeryGoodOpenSource/very_good_cli#735]
**Description**
Hello
I Luv Very good cli
I has iusse yesterday
An error occurs when starting a project with Very good cli in a flutter 3.10.0 environment.

**Expected Behavior**
Because remove_app depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.

**Screenshots**
<img width="558" alt="스크린샷 2023-05-12 오후 2 34 07" src="https://github.com/VeryGoodOpenSource/very_good_cli/assets/34917143/2e8bdf93-6c65-4e36-b5c5-5a95c6e8c597">

**Additional Context**

**Comment by mariopepe** [comment]
@BGM-109 its enough to update the pubspec.yaml it is easy....

```yaml
name: my_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
```
