### ISSUE TITLE
fix: `very_good packages get -r` silently quits if there is no `flutter` executable available

### ISSUE THREAD

**Issue by incendial** [VeryGoodOpenSource/very_good_cli#760]
**Description**
Hello!

When using `very_good packages get -r` on CI without Flutter being installed, the command silently quits without installing the dependencies. This behaviour is kinda misleading and a warning of some sort would be great to have.

For example,
```yaml
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Beta Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: beta

      - name: Install Very Good CLI
        run: |
          dart pub global activate very_good_cli
          dart pub global run very_good_cli:very_good --analytics=false

      - name: Install dependencies
        run: dart pub global run very_good_cli:very_good packages get -r
```

The output looks like:
<img width="760" alt="Screenshot 2023-07-10 at 14 36 48" src="https://github.com/VeryGoodOpenSource/very_good_cli/assets/21116742/a4565f6a-0a28-44f1-b312-e00f003c00b5">

**Steps To Reproduce**

1. Create a github workflow with the steps above
2. Run it
