### ISSUE TITLE
[CI - test_optimizer] GitHub Actions, Melos, very_good test lead sometimes to cache error 

### ISSUE THREAD

**Issue by md-weber** [VeryGoodOpenSource/very_good_cli#947]
**Description**
We use GitHub Actions with the caching support of the `subosito/flutter-action@v2` together with Melos and every now and then we run into the following error:

`cache/bundled/test_optimizer_0.1.0+1_e324e538d331470906db7fbaea6b8d957bcce68d/hooks/build/hooks/pre_gen/pre_gen_7389adb0f4462262bdd04123d3826c0231f89ed6.dart': No such file or directory`

Melos config looks like this:
```yaml
  ci:test:
    run: |
      melos exec -c 4 -- \
        very_good test --coverage --test-randomize-ordering-seed random
```

**Steps To Reproduce**
- Create a minimal project with melos multiple packages
- Add a CI with GitHub Actions
- Run very_good test with 4 concurrencies via melos in all packages

**Expected Behavior**
No error

**Additional Context**
I know that is not a perfect issue, but any help is much appreciated.

**Comment by tomarra** [comment]
Hi @md-weber 👋 Thanks for opening up an issue.

Would you be able to provide a sample project that can clearly demonstrate this? We don't tend to work with a lot of projects using Melos so want to make sure we are not spinning our wheels or trying something different then what your putting together. One other thing to ask is if you have tried this without the concurrency flag. We have seen some issues with that in the past and would like to be able to rule that out quickly if possible.

Thanks in advance and looking forward to your reply.

**Comment by md-weber** [comment]
Hi @tomarra thanks for your answer, I will work on a demo example this weekend and hope that I can provide you an example till next week.

At the moment we did exactly that to at least not see the warning anymore. As soon the concurrency is out, it works flawless. If that just mean we cannot use concurrency in Melos it is still good to have that issue so that people know about it 👍

**Comment by opanitch** [comment]
hey, is there any movement on this issue?  It really affects us when running our test suites in a Mac VM (in CodeMagic).  Removing the optimization seems to work to avoid the issue, but drastically slows the testing suite - almost doubles the timing.

**Comment by mdikcinar** [comment]
Hello, I encountered the same issue. While investigating the problem, I came across two errors.

The first one was:
`- [ERROR] loading /Users/builder/clone/packages/package-name/test/.test_optimizer.dart
`
I resolved this by using the **--keep-optimizers** flag. However, after that, I ran into a second issue:

```
Unable to compile hook: /Users/builder/.mason-cache/bundled/test_optimizer_0.1.0+1_ac31492dca4c5aad3d5ac403016a8aa398923b65/hooks/pre_gen.dart.
Error: ../../../.mason-cache/bundled/test_optimizer_0.1.0+1_ac31492dca4c5aad3d5ac403016a8aa398923b65/hooks/build/hooks/pre_gen/pre_gen_3e8e8a2b6feef36fcf68e4c345dab6c6e17cd21a.dart: Error: Error when reading '../../../.mason-cache/bundled/test_optimizer_0.1.0+1_ac31492dca4c5aad3d5ac403016a8aa398923b65/hooks/build/hooks/pre_gen/pre_gen_3e8e8a2b6feef36fcf68e4c345dab6c6e17cd21a.dart': No such file or directory
../../../.mason-cache/bundled/test_optimizer_0.1.0+1_ac31492dca4c5aad3d5ac403016a8aa398923b65/hooks/build/hooks/pre_gen/pre_gen_3e8e8a2b6feef36fcf68e4c345dab6c6e17cd21a.dart: Error: No 'main' method found.
Try adding a method named 'main' to your program.
Bad state: Generating kernel failed!
```
To resolve this, I added a queue system for the test optimizer file. After that, everything worked as expected.
You can check my solution here: 
https://github.com/mdikcinar/very_good_cli/tree/feature/keep-optimizers

My scenario
``` 
  ciTest:
    name: CI Test
    description: Run `very_good test` for selected packages.
    run: melos exec --fail-fast -c 4 -- "very_good test --keep-optimizers -- --fail-fast"
    packageFilters:
      dirExists: test
```
Note: Fail fast not working on melos 6.2.0 
https://github.com/invertase/melos/pull/665#issuecomment-2755686786

```
    scripts:
      - *initialize_project
      - name: Very Good CLI install
        script: |
          dart pub global activate --source git https://github.com/mdikcinar/very_good_cli.git --git-ref f11b477cb010c62b4290e6e687be32803ed3838d
      - name: Melos Test
        script: |
          TZ=Asia/Istanbul melos run ciTest
```
